NUM_R_THREADS = 2
NUM_W_THREADS = 2
BLOCKS_IN_MEMORY = 2000000
SEED = 1234
RUNS = 1
REPEAT = 1
SHORT_RANGE_QUERIES = 0
MID_RANGE_QUERIES = 0
LONG_RANGE_QUERIES = 0
RAW_READS_PERCENTAGE = 10
RAW_WRITES_PERCENTAGE = 0
MIXED_LOAD_PERCENTAGE = 0
UPDATES_PERCENTAGE = 0
RESULTS_FILE = "results.csv"
