BLOCKS_IN_MEMORY = 4000000
SEED = 1234
RUNS = 1
REPEAT = 1
SHORT_RANGE_QUERIES = 0
MID_RANGE_QUERIES = 0
LONG_RANGE_QUERIES = 0
RAW_READS_PERCENTAGE = 1
RAW_WRITES_PERCENTAGE = 0
MIXED_LOAD_PERCENTAGE = 0
UPDATES_PERCENTAGE = 0
SWARE_FILL_FACTOR = 95