CXXFLAGS=-Isrc/bptree -std=c++17 -DINMEMORY
TARGET=src/tree_analysis.cpp
EXE_DIR=trees

all: trees

trees: clean
	$(CXX) $(CXXFLAGS) -DBENCHMARK $(TARGET) -o $(EXE_DIR)/1_simple
	$(CXX) $(CXXFLAGS) -DTAIL_FAT -DBENCHMARK $(TARGET) -o $(EXE_DIR)/2_tail
	$(CXX) $(CXXFLAGS) -DLIL_FAT -DBENCHMARK $(TARGET) -o $(EXE_DIR)/3_lil
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DBENCHMARK $(TARGET) -o $(EXE_DIR)/4_plainlol
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DBENCHMARK $(TARGET) -o $(EXE_DIR)/5_lol_v
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DBENCHMARK $(TARGET) -o $(EXE_DIR)/6_lol_vi
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DREDISTRIBUTE -DBENCHMARK $(TARGET) -o $(EXE_DIR)/7_lol_vir
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DREDISTRIBUTE -DBENCHMARK -DLOL_RESET=0 $(TARGET) -o $(EXE_DIR)/7_lol_vir_0
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DREDISTRIBUTE -DBENCHMARK -DLOL_RESET=1 $(TARGET) -o $(EXE_DIR)/7_lol_vir_1
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DREDISTRIBUTE -DBENCHMARK -DLOL_RESET=2 $(TARGET) -o $(EXE_DIR)/7_lol_vir_2
	$(CXX) $(CXXFLAGS) -DBENCHMARK $(TARGET) -O3 -o $(EXE_DIR)/O3_1_simple
	$(CXX) $(CXXFLAGS) -DTAIL_FAT -DBENCHMARK $(TARGET) -O3 -o $(EXE_DIR)/O3_2_tail
	$(CXX) $(CXXFLAGS) -DLIL_FAT -DBENCHMARK $(TARGET) -O3 -o $(EXE_DIR)/O3_3_lil
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DBENCHMARK $(TARGET) -O3 -o $(EXE_DIR)/O3_4_plainlol
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DBENCHMARK $(TARGET) -O3 -o $(EXE_DIR)/O3_5_lol_v
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DBENCHMARK $(TARGET) -O3 -o $(EXE_DIR)/O3_6_lol_vi
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DREDISTRIBUTE -DBENCHMARK $(TARGET) -O3 -o $(EXE_DIR)/O3_7_lol_vir
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DREDISTRIBUTE -DBENCHMARK -DLOL_RESET=0 $(TARGET) -O3 -o $(EXE_DIR)/O3_7_lol_vir_0
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DREDISTRIBUTE -DBENCHMARK -DLOL_RESET=1 $(TARGET) -O3 -o $(EXE_DIR)/O3_7_lol_vir_1
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DREDISTRIBUTE -DBENCHMARK -DLOL_RESET=2 $(TARGET) -O3 -o $(EXE_DIR)/O3_7_lol_vir_2

simple:
	$(CXX) $(CXXFLAGS) $(TARGET) -o $(EXE_DIR)/$@

tail:
	$(CXX) $(CXXFLAGS) -DTAIL_FAT $(TARGET) -o $(EXE_DIR)/$@

lil:
	$(CXX) $(CXXFLAGS) -DLIL_FAT $(TARGET) -o $(EXE_DIR)/$@

plainlol:
	$(CXX) $(CXXFLAGS) -DLOL_FAT $(TARGET) -o $(EXE_DIR)/$@

lol:
	$(CXX) $(CXXFLAGS) -DLOL_FAT -DVARIABLE_SPLIT -DDOUBLE_IQR -DREDISTRIBUTE -DLOL_RESET $(TARGET) -o $(EXE_DIR)/$@

clean:
	mkdir -p $(EXE_DIR)
	rm -f $(EXE_DIR)/*
