BLOCKS_IN_MEMORY = 2000000
RAW_READS_PERCENTAGE = 0
RAW_WRITES_PERCENTAGE = 0
MIXED_WRITES_PERCENTAGE = 0
MIXED_READ_PERCENTAGE = 0
UPDATES_PERCENTAGE = 0
SHORT_RANGE_QUERIES = 0
MID_RANGE_QUERIES = 0
LONG_RANGE_QUERIES = 0
RUNS = 1
REPEAT = 1
SEED = 1234
NUM_THREADS = 32
RESULTS_FILE = "results.csv"
BINARY_INPUT = true
VALIDATE = false
